In [8]:
import numpy as np

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [10]:
type(a)

numpy.ndarray

basic operation of array

In [11]:
print(a + b)
print(a - b)
print(a * b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [12]:
#creating a 2D array
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
print(a.shape)#(2,2,2) 2 arrays, 2 rows, 2 columns

(2, 2)


In [15]:
print(a.ndim)

2


In [16]:
print(a.dtype)

int64


In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [19]:
np.random.randint(10,30, size=(3,3))

array([[20, 19, 14],
       [21, 26, 10],
       [13, 14, 17]], dtype=int32)

In [20]:
x = np.array([[7,2,3],
              [2,5,2],
              [3,5,1]])

y = np.array([[1,8,3],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 3]
 [3 7 2]
 [2 5 3]]


In [21]:
print(x.dot(y))#matrix multiplication

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [22]:
x.prod()#it gives multiplication of all the elements of the array

np.int64(12600)

In [23]:
print(x@y)

[[19 85 34]
 [21 61 22]
 [20 64 22]]


In [24]:
x.mean()# is gives the mean of all the elements of the array

np.float64(3.3333333333333335)

In [25]:
x.mean(axis=0)# its gives the mean of each columns

array([4., 4., 2.])

In [26]:
x.mean(axis=1)# its gives the mean of each rows

array([4., 3., 3.])

In [27]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) #it gives the variance of all the elements of the array
print(x.std()) #it gives the standard deviation of all the elements of the story


30
3.3333333333333335
1.8257418583505538


In [28]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a, 25))# it gives the 25th percentile of the array
print(np.percentile(a, 50))# it gives the 50th percentile of the array
print(np.percentile(a, 75))# it gives the 75th percentile of the array

3.0
5.0
7.0


In [29]:
arr = np.random.randint(10,30, size=(4,4))
print(arr)

[[15 17 16 18]
 [27 15 20 14]
 [17 10 13 21]
 [14 13 20 16]]


In [31]:
print('2x8')
print(arr.reshape(2,8))
      


2x8
[[15 17 16 18 27 15 20 14]
 [17 10 13 21 14 13 20 16]]


In [34]:
print(x[0])
print(x[0,0])
print(x[0,1])

[7 2 3]
7
2


In [37]:
print(x[:3])
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[3 5 1]]
